git:
  autoFetch: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - reverse

